I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/NadinNightmare1Script.rpy", line 24, in script
    jump helpedInFirst
ScriptError: could not find label 'helpedInFirst'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/NadinNightmare1Script.rpy", line 24, in script
    jump helpedInFirst
  File "renpy/ast.py", line 1751, in execute
    rv = renpy.game.script.lookup(target)
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'helpedInFirst'.

Windows-10-10.0.19041
Ren'Py 7.4.6.1693
NCRvn 1.0
Sat Jul  3 18:18:26 2021
